### ISSUE TITLE
Ошибка 404 для regex

### ISSUE THREAD

**Issue by kogleron** [Uma-Tech/parrot#68]
Для настроек
Request path: `/variator/decide.*?uuid=device-403`
REGEX path: checked

При запросе ниже получаю 404 ответ.
`/variator/decide?srv=premier&uuid=device-403&reqid=99e5e58131e01154d83b797c1df4b331&device=web&useragent=curl%2F7.64.1&url=%2Fsome%2Fpath&region=WW&timestamp=1605703283.983`

Для настроек
Request path: `^/variator/decide\?srv=premier&((?!uuid=device-403).)*$`
REGEX path: checked

При запросе ниже получаю 404 ответ.
`/variator/decide?srv=premier&uuid=device-200&reqid=99e5e58131e01154d83b797c1df4b331&device=web&useragent=curl%2F7.64.1&url=%2Fsome%2Fpath&region=WW&timestamp=1605703283.983`

**Comment by lowitea** [comment]
Кажется всё работает правильно, регэксп не матчится, потому что не экранированы спец символы, проверить можно тут: https://regex101.com/r/qc2sin/1

**Comment by lowitea** [comment]
Если есть возможность, прошу заводить ишью на английском языке, так понимать о чём речь смогут не только рускоговорящие

**Comment by kogleron** [comment]
> Кажется всё работает правильно, регэксп не матчится, потому что не экранированы спец символы, проверить можно тут: https://regex101.com/r/qc2sin/1

^/variator/decide\?srv=premier&((?!uuid=device-403).)*$ дает 404 ответ.

https://regex101.com/r/qc2sin/2
